include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for qBittorrent-enhanced
LUCI_DEPENDS:=+python3 +qBittorrent-enhanced
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-qBittorrent-enhanced
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk
